import os
import tempfile
from fpdf import FPDF
import io

class PDFReport(FPDF):
    def header(self):
        # Logo
        if os.path.exists("logo.png"):
            # Position logo at top right
            self.image("logo.png", x=165, y=10, w=30)
        
        # Title
        self.set_font("Helvetica", style="B", size=20)
        self.set_text_color(0, 173, 181) # Teal color (#00ADB5)
        self.cell(0, 10, "FazDane Analytics", new_x="LMARGIN", new_y="NEXT", align="L")
        
        # Subtitle
        self.set_font("Helvetica", style="B", size=12)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, "Volatility Engine Report", new_x="LMARGIN", new_y="NEXT", align="L")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", style="I", size=8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by FazDane Analytics Strategy Engine", align="C")

def generate_pdf_report(ticker, company_name, current_price, result, fig_vol, fig_term):
    """
    Generates a 1-pager PDF report and returns it as a byte string for Streamlit download.
    """
    pdf = PDFReport(orientation="portrait", format="A4")
    pdf.add_page()
    
    # --- TICKER INFO ---
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, f"{ticker} - {company_name}", new_x="LMARGIN", new_y="NEXT", align="L")
    
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Current Price: ${current_price:,.2f}", new_x="LMARGIN", new_y="NEXT", align="L")
    pdf.ln(5)

    # --- STRATEGY OUTPUT BOX ---
    pdf.set_fill_color(245, 248, 250)
    pdf.set_draw_color(0, 173, 181)
    pdf.set_line_width(0.5)
    
    # We use a cell to draw the background box
    pdf.set_font("Helvetica", style="B", size=14)
    pdf.set_text_color(0, 173, 181)
    pdf.cell(0, 10, "🎯 Strategy Recommendation", border="TLR", fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    
    pdf.set_font("Helvetica", style="B", size=16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, result['strategy'], border="LR", fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    
    # Confidence color logic
    conf = result['confidence']
    if conf == "High":
        pdf.set_text_color(82, 214, 138) # Green
    elif conf == "Medium":
        pdf.set_text_color(220, 180, 0)  # Yellow-ish
    else:
        pdf.set_text_color(255, 107, 107) # Red
        
    pdf.set_font("Helvetica", style="B", size=11)
    pdf.cell(0, 8, f"Confidence: {conf}", border="LR", fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    
    pdf.set_text_color(80, 80, 80)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(95, 8, f"Target DTE: {result['dte_rec']}", border="L", fill=True, align="R")
    pdf.cell(95, 8, f"Strike: {result['strike_note']}", border="R", fill=True, new_x="LMARGIN", new_y="NEXT", align="L")
    
    # Reason
    # We use multi_cell for the long reason text
    pdf.set_font("Helvetica", style="I", size=9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, result['reason'], border="BLR", fill=True, align="C")
    pdf.ln(8)

    # --- GRAPHS ---
    pdf.set_font("Helvetica", style="B", size=14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Volatility Analysis", new_x="LMARGIN", new_y="NEXT", align="L")
    pdf.ln(2)

    # Save Plotly figs to temp PNGs via Kaleido
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f_vol:
        vol_path = f_vol.name
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f_term:
        term_path = f_term.name

    try:
        # Resize fig prior to export to fit PDF nicely
        fig_vol.update_layout(width=800, height=450, margin=dict(l=20, r=20, t=40, b=20))
        fig_term.update_layout(width=800, height=450, margin=dict(l=20, r=20, t=40, b=20))
        
        fig_vol.write_image(vol_path, engine="kaleido", scale=2)
        fig_term.write_image(term_path, engine="kaleido", scale=2)
        
        # Calculate width to fit page
        # A4 width is 210mm. Margins are 10mm each side -> 190mm usable width.
        pdf.image(vol_path, w=190)
        pdf.ln(5)
        pdf.image(term_path, w=190)
        
    finally:
        # Clean up temp files
        if os.path.exists(vol_path):
            os.remove(vol_path)
        if os.path.exists(term_path):
            os.remove(term_path)

    # Output to bytearray
    return bytes(pdf.output())
